hibernate:
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    #provider_class: net.sf.ehcache.hibernate.EhCacheProvider
    region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
spring:
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
    username: sa
    password:
  groovy:
    template:
      check-template-location: false
dataSource:
  pooled: true
  dbCreate: create-drop
  logSql: true
server:
  port: 8090